version: '3.8'
services:

  stats-server:
    build: stats/stats-server
    image: stats-server
    container_name: stats-server
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  stats-db:
    image: postgres:14-alpine
    container_name: stats-server-db
    restart: always
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
    volumes:
      - /var/lib/postgresql/data/


  main-service:
    build: main-service
    image: main-service
    container_name: main-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  main-db:
    image: postgres:14-alpine
    container_name: main-service-db
    restart: always
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
    volumes:
      - /var/lib/postgresql/data/