version: '3.1'
services:
  main-service:
    container_name: main-service
    build: ./main-service
    ports:
      - "8080:8080"
    depends_on:
      - stats
    environment:
      - STAT_SERVER_URL=http://stats-server:9090

  stats:
    build: ./stats/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - DB_HOST=db
      - DB_PORT=5432

  stats-db:
    image: postgres:13.7-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot